---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Set up filters for traefik auth
  template:
    src: traefik-auth.conf.j2
    dest: /etc/fail2ban/filter.d/traefik-auth.conf
  when: fail2ban_use_traefik_filters

- name: Set up filters for traefik bots
  template:
    src: traefik-botsearch.conf.j2
    dest: /etc/fail2ban/filter.d/traefik-botsearch.conf
  when: fail2ban_use_traefik_filters

- name: Set up jails
  template:
    src: jails.local.j2
    dest: /etc/fail2ban/jail.d/jails.local
  notify:
   - restart fail2ban

