- name: install ufw
  apt:
    name: ufw
    state: latest

- name: ufw deny incoming
  ufw:
    direction: incoming
    proto: any
    policy: deny
  notify:
    - reload ufw
  when: ufw_deny_all_incoming | bool == true

- name: ufw allow outgoing
  ufw:
    direction: outgoing
    proto: any
    policy: allow
  notify:
    - reload ufw
  when: ufw_allow_all_outgoing | bool == true

- name: ufw allow specific ports in
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  notify:
    - reload ufw
  loop: "{{ ufw_allowed_ports_in }}"

- name: enable ufw service
  ufw:
    state: enabled