- name: Add Grafana repository signing key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Install Grafana apt repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Install promtail
  apt:
    name: promtail
    state: present

- name: Add promtail user to adm group to access journal
  user:
    name: promtail
    groups: adm
    append: true

- name: Create positions dir
  file:
    path: "{{ promtail_config_positions_dir }}"
    state: directory
    owner: promtail
    group: adm
    mode: '0770'